package com.abc.lzabcmode.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.abc.lzabcmode.greendao.LuckyNumberData;

import com.abc.lzabcmode.greendao.LuckyNumberDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig luckyNumberDataDaoConfig;

    private final LuckyNumberDataDao luckyNumberDataDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        luckyNumberDataDaoConfig = daoConfigMap.get(LuckyNumberDataDao.class).clone();
        luckyNumberDataDaoConfig.initIdentityScope(type);

        luckyNumberDataDao = new LuckyNumberDataDao(luckyNumberDataDaoConfig, this);

        registerDao(LuckyNumberData.class, luckyNumberDataDao);
    }
    
    public void clear() {
        luckyNumberDataDaoConfig.clearIdentityScope();
    }

    public LuckyNumberDataDao getLuckyNumberDataDao() {
        return luckyNumberDataDao;
    }

}
