package com.abc.lzabcmode.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "LUCKY_NUMBER_DATA".
*/
public class LuckyNumberDataDao extends AbstractDao<LuckyNumberData, Long> {

    public static final String TABLENAME = "LUCKY_NUMBER_DATA";

    /**
     * Properties of entity LuckyNumberData.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property Time = new Property(1, String.class, "time", false, "TIME");
        public final static Property IssueNumber = new Property(2, String.class, "IssueNumber", false, "ISSUE_NUMBER");
        public final static Property LuckyArrays = new Property(3, String.class, "luckyArrays", false, "LUCKY_ARRAYS");
    }


    public LuckyNumberDataDao(DaoConfig config) {
        super(config);
    }
    
    public LuckyNumberDataDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"LUCKY_NUMBER_DATA\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL ," + // 0: id
                "\"TIME\" TEXT NOT NULL ," + // 1: time
                "\"ISSUE_NUMBER\" TEXT NOT NULL ," + // 2: IssueNumber
                "\"LUCKY_ARRAYS\" TEXT NOT NULL );"); // 3: luckyArrays
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"LUCKY_NUMBER_DATA\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, LuckyNumberData entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindString(2, entity.getTime());
        stmt.bindString(3, entity.getIssueNumber());
        stmt.bindString(4, entity.getLuckyArrays());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, LuckyNumberData entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindString(2, entity.getTime());
        stmt.bindString(3, entity.getIssueNumber());
        stmt.bindString(4, entity.getLuckyArrays());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public LuckyNumberData readEntity(Cursor cursor, int offset) {
        LuckyNumberData entity = new LuckyNumberData( //
            cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // time
            cursor.getString(offset + 2), // IssueNumber
            cursor.getString(offset + 3) // luckyArrays
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, LuckyNumberData entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setTime(cursor.getString(offset + 1));
        entity.setIssueNumber(cursor.getString(offset + 2));
        entity.setLuckyArrays(cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(LuckyNumberData entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(LuckyNumberData entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(LuckyNumberData entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
